// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxmitvdpzltgjxpersts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4bWl0dmRwemx0Z2p4cGVyc3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDkwNDksImV4cCI6MjA2OTEyNTA0OX0.kxkq4jeZRfOBCWTfxmIP1N8KEiOPtIl4ubFm9GXyfiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});